version: '3.8'

services:
  mlflow:
    image: mlflow-tracking
    build:
      context: .
      dockerfile: mlflow.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    environment:
      - BACKEND_STORE_URI=sqlite:////mlruns/mlflow.db
      - ARTIFACT_ROOT=/mlruns/artifacts

  ml_training:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mlflow
    volumes:
      - ./data:/app/data
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_EXPERIMENT_NAME=sales_forecast

  jupyter:
    image: jupyter/datascience-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes